"""
Tablas de respaldo del cribado jurídico, generadas desde la investigación documental
del 15 de agosto de 2026. NO editar a mano: son el plan B para cuando los servicios
de la ANT o de la URT no respondan. La consulta viva en juridico.py tiene precedencia.

UAF: rangos agregados por municipio. Donde hay acuerdo UAF por UFH del Consejo
Directivo de la ANT (Acuerdo 167 de 2021 y acuerdos municipales 2023-2026), el rango
es el agregado de las UFH del municipio según la capa oficial ANT; donde no, aplica
la Resolución 041 de 1996 del INCORA (régimen de transición de la Resolución ANT
202510303779576 del 30-dic-2025).

Restitución: solicitudes históricas de inscripción al SRTDAF por municipio del
predio (Ley 1448 de 2011, vigente hasta 2031 por la Ley 2078 de 2021), dataset URT
33hn-pgph con corte 2026-07-31, contrastado con s87b-tjcc. microzona indica si hay
microzona focalizada de la URT vigente en el municipio (FeatureServer Open_Data_Microzonas).
"""

UAF_FALLBACK = {
    "13140": {"municipio": "Calamar", "departamento": "Bolívar",
        "uaf_min_ha": 35, "uaf_max_ha": 47,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "13433": {"municipio": "Mahates", "departamento": "Bolívar",
        "uaf_min_ha": 26, "uaf_max_ha": 48,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "20710": {"municipio": "San Alberto", "departamento": "Cesar",
        "uaf_min_ha": 3.99, "uaf_max_ha": 28.22,
        "acto": "Acuerdo ANT 546/2025", "confianza": "alta"},
    "23068": {"municipio": "Ayapel", "departamento": "Córdoba",
        "uaf_min_ha": 5.21, "uaf_max_ha": 29.29,
        "acto": "Acuerdo ANT 304/2023", "confianza": "alta"},
    "23079": {"municipio": "Buenavista", "departamento": "Córdoba",
        "uaf_min_ha": 3.69, "uaf_max_ha": 20.08,
        "acto": "Acuerdo ANT 546/2025", "confianza": "alta"},
    "23182": {"municipio": "Chinú", "departamento": "Córdoba",
        "uaf_min_ha": 4.27, "uaf_max_ha": 18.21,
        "acto": "Acuerdo ANT 546/2025", "confianza": "alta"},
    "23350": {"municipio": "La Apartada", "departamento": "Córdoba",
        "uaf_min_ha": 3.05, "uaf_max_ha": 24.61,
        "acto": "Acuerdo ANT 546/2025", "confianza": "alta"},
    "23464": {"municipio": "Momil", "departamento": "Córdoba",
        "uaf_min_ha": 3.27, "uaf_max_ha": 21.22,
        "acto": "Acuerdo ANT 521/2025", "confianza": "alta"},
    "23466": {"municipio": "Montelíbano", "departamento": "Córdoba",
        "uaf_min_ha": 36, "uaf_max_ha": 49,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "23555": {"municipio": "Planeta Rica", "departamento": "Córdoba",
        "uaf_min_ha": 3.75, "uaf_max_ha": 19.35,
        "acto": "Acuerdo ANT 307/2023", "confianza": "alta"},
    "23570": {"municipio": "Pueblo Nuevo", "departamento": "Córdoba",
        "uaf_min_ha": 3.08, "uaf_max_ha": 20.04,
        "acto": "Acuerdo ANT 546/2025", "confianza": "alta"},
    "23580": {"municipio": "Puerto Libertador", "departamento": "Córdoba",
        "uaf_min_ha": 36, "uaf_max_ha": 49,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "23682": {"municipio": "San José de Uré", "departamento": "Córdoba",
        "uaf_min_ha": 36, "uaf_max_ha": 49,
        "acto": "Res. 041/1996 INCORA", "confianza": "media"},
    "41524": {"municipio": "Palermo", "departamento": "Huila",
        "uaf_min_ha": 2.89, "uaf_max_ha": 22.51,
        "acto": "Acuerdo ANT 437/2024", "confianza": "alta"},
    "41799": {"municipio": "Tello", "departamento": "Huila",
        "uaf_min_ha": 2.76, "uaf_max_ha": 13.23,
        "acto": "Acuerdo ANT 416/2024", "confianza": "alta"},
    "41885": {"municipio": "Yaguará", "departamento": "Huila",
        "uaf_min_ha": 35, "uaf_max_ha": 58,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "50226": {"municipio": "Cumaral", "departamento": "Meta",
        "uaf_min_ha": 7.94, "uaf_max_ha": 40.54,
        "acto": "Acuerdo ANT 574/2026", "confianza": "alta"},
    "54385": {"municipio": "La Esperanza", "departamento": "Norte de Santander",
        "uaf_min_ha": 14, "uaf_max_ha": 50,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "68655": {"municipio": "Sabana de Torres", "departamento": "Santander",
        "uaf_min_ha": 18, "uaf_max_ha": 33,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "70124": {"municipio": "Caimito", "departamento": "Sucre",
        "uaf_min_ha": 4.58, "uaf_max_ha": 31.06,
        "acto": "Acuerdo ANT 545/2025", "confianza": "alta"},
    "70233": {"municipio": "El Roble", "departamento": "Sucre",
        "uaf_min_ha": 4.75, "uaf_max_ha": 23.97,
        "acto": "Acuerdo ANT 574/2026", "confianza": "alta"},
    "70400": {"municipio": "La Unión", "departamento": "Sucre",
        "uaf_min_ha": 5.48, "uaf_max_ha": 30.54,
        "acto": "Acuerdo ANT 545/2025", "confianza": "alta"},
    "70523": {"municipio": "Palmito", "departamento": "Sucre",
        "uaf_min_ha": 36, "uaf_max_ha": 49,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "70708": {"municipio": "San Marcos", "departamento": "Sucre",
        "uaf_min_ha": 31, "uaf_max_ha": 72,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
    "70820": {"municipio": "Santiago de Tolú", "departamento": "Sucre",
        "uaf_min_ha": 3.8, "uaf_max_ha": 27.72,
        "acto": "Acuerdo ANT 506/2025", "confianza": "alta"},
    "70823": {"municipio": "San José de Toluviejo", "departamento": "Sucre",
        "uaf_min_ha": 4.48, "uaf_max_ha": 36.69,
        "acto": "Acuerdo ANT 506/2025", "confianza": "alta"},
    "76113": {"municipio": "Bugalagrande", "departamento": "Valle del Cauca",
        "uaf_min_ha": 4, "uaf_max_ha": 6,
        "acto": "Res. 041/1996 INCORA", "confianza": "media"},
    "76895": {"municipio": "Zarzal", "departamento": "Valle del Cauca",
        "uaf_min_ha": 4, "uaf_max_ha": 6,
        "acto": "Res. 041/1996 INCORA", "confianza": "alta"},
}

RESTITUCION_FALLBACK = {
    "13140": {"municipio": "Calamar", "solicitudes": 137, "microzona": False},
    "13433": {"municipio": "Mahates", "solicitudes": 54, "microzona": True},
    "20710": {"municipio": "San Alberto", "solicitudes": 562, "microzona": True},
    "23068": {"municipio": "Ayapel", "solicitudes": 171, "microzona": True},
    "23079": {"municipio": "Buenavista", "solicitudes": 66, "microzona": True},
    "23182": {"municipio": "Chinú", "solicitudes": 24, "microzona": False},
    "23350": {"municipio": "La Apartada", "solicitudes": 21, "microzona": True},
    "23464": {"municipio": "Momil", "solicitudes": 5, "microzona": False},
    "23466": {"municipio": "Montelíbano", "solicitudes": 431, "microzona": True},
    "23555": {"municipio": "Planeta Rica", "solicitudes": 77, "microzona": True},
    "23570": {"municipio": "Pueblo Nuevo", "solicitudes": 430, "microzona": True},
    "23580": {"municipio": "Puerto Libertador", "solicitudes": 308, "microzona": True},
    "23682": {"municipio": "San José de Uré", "solicitudes": 459, "microzona": True},
    "41524": {"municipio": "Palermo", "solicitudes": 65, "microzona": False},
    "41799": {"municipio": "Tello", "solicitudes": 120, "microzona": True},
    "41885": {"municipio": "Yaguará", "solicitudes": 2, "microzona": True},
    "50226": {"municipio": "Cumaral", "solicitudes": 36, "microzona": True},
    "54385": {"municipio": "La Esperanza", "solicitudes": 177, "microzona": True},
    "68655": {"municipio": "Sabana de Torres", "solicitudes": 681, "microzona": True},
    "70124": {"municipio": "Caimito", "solicitudes": 6, "microzona": True},
    "70233": {"municipio": "El Roble", "solicitudes": 37, "microzona": True},
    "70400": {"municipio": "La Unión", "solicitudes": 7, "microzona": False},
    "70523": {"municipio": "Palmito", "solicitudes": 17, "microzona": False},
    "70708": {"municipio": "San Marcos", "solicitudes": 35, "microzona": False},
    "70820": {"municipio": "Santiago de Tolú", "solicitudes": 249, "microzona": False},
    "70823": {"municipio": "Tolú Viejo", "solicitudes": 145, "microzona": True},
    "76113": {"municipio": "Bugalagrande", "solicitudes": 420, "microzona": True},
    "76895": {"municipio": "Zarzal", "solicitudes": 26, "microzona": True},
}
